language: generic

sudo: required

services:
  - docker
  
install:
  - docker run -d --name buildenv -v "$(pwd):/project" mkacz/buildenv:initial
  - docker logs buildenv
  - alias dex='docker exec -tiu build buildenv sh /container-utils/exec.sh'
  - shopt -s expand_aliases
  
script:
  - dex ls /
  - dex cmake /project/test
  - dex make
  - dex ./run_tests
